### ISSUE TITLE
node install error 

### ISSUE THREAD

**Issue by aspxnetcore** [wx1993/node-vue-fabaocn#1]
$ node install
module.js:471
    throw err;
    ^
Error: Cannot find module c:\node-vue-fabaocn\install'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

**Comment by wx1993** [comment]
it should be "npm install" instead of "node install"...
