### ISSUE TITLE
webpack -w  报了很多错？

### ISSUE THREAD

**Issue by dpc761218914** [wx1993/node-vue-fabaocn#2]
WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./src/main.js
Module build failed: Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (E:\vueProject\node-vue-fabaocn-master\node_modules\babel-loader\lib\index.js:3:13)
    at Module._compile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at loadLoader (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\NormalModule.js:235:3)
    at NormalModule.build (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\NormalModule.js:365:15)
    at Compilation.buildModule (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:362:10)
    at moduleFactory.create (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:711:12)
    at factory (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
    at hooks.afterResolve.callAsync (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook [as _callAsync] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at resolver (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\NormalModuleFactory.js:126:29)
    at process.nextTick (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\NormalModuleFactory.js:304:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

E:\vueProject\node-vue-fabaocn-master>webback -v
'webback' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

E:\vueProject\node-vue-fabaocn-master>webpack -v
4.8.1

E:\vueProject\node-vue-fabaocn-master>

**Comment by wx1993** [comment]
webpack 安装了吗
